### ISSUE TITLE
Disable completion

### ISSUE THREAD

**Issue by petewall** [petewall/eink-radiator-image-source-image#1]
These components don't need to support shell completion, so we should add this line:

`rootCmd.CompletionOptions.DisableDefaultCmd = true`

**Comment by amoghrajesh** [comment]
@petewall I would like to work on this issue. Can you assign it to me and point me where i should start?

**Comment by petewall** [comment]
Awesome!
A few things to get started. Make sure you can

**Comment by amoghrajesh** [comment]
@petewall can you assign it to me?

**Comment by petewall** [comment]
The real issue is when you run `./build/image -h` it shows "completion" as a subcommand. I don't want that. Adding the one-liner in the issue description will turn that off. That line should go in a new `func init() {}` in `root.go`.
